#!/bin/sh
if [ "$1" = '-h' ]; then cat <<EOF
Usage: ./aindex [ <URL> | -h ]
aindex retrieves webpage http://index.hu/napirajz, downloads the
comics to the working dir and creates aindex.html with links to them.
The name of the created filename is printed to stdout.
ATTENTION developer: do not print anything else to stdout!!!
EOF
exit 0
fi

# Get archive URL in arg1, otherwise generate main page. Generate filename.
echo >&2 "****************** aindex debug message *******************"
URL="http://index.hu/napirajz/"
FILE="aindex.html"
echo >&2 "$FILE from $URL"

# Get picture URLs
curl -f ${URL} 2>/dev/null | grep '<span class="imageholder clearafter"><img id=' > tmp
[ `ls -l tmp | awk '{ print $5 }'` = 0 ] && echo >&2 "No pics found" && exit 1

# Print page header
which perl >/dev/null && EXTENSION=pl || EXTENSION=cgi
cat > $FILE <<HEADER
<html><head><title>subogero aindex</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head><body>
<a href="index.html">napi</a>
<a href="tegnapi.html">tegnapi</a>
<a href="komedia.html">kom&eacute;dia</a>
<a href="aindex.html">aindex</a>
<a href="keres.${EXTENSION}">keres</a>
<hr><h3 align="center">subogero aindex</h3><hr>
HEADER

# Get pictures and print links to copies
uname -a | grep -i wrt >/dev/null || WGETOPT=-nc
while read i; do
  URL=`echo $i | sed -rn 's/^.+src="(.+)" alt=.+$/\1/p'`
  PIC=`echo $i | sed -rn 's:^.+src=".+/([0-9_a-fwm]+\.jpg)" alt=.+$:\1:p'`
  ALT=`echo $i | sed -rn 's/^.+alt="(.+)" width=.+$/\1/p' |  sed 's/ /_/g'`
  if [ ! -f "${ALT}.jpg" ]; then
    wget ${WGETOPT} "${URL}"
    mv $PIC ${ALT}.jpg
  fi
  echo "<a href=\"mutat.pl?rajz=${ALT}.jpg\">${ALT}</a><br>" >> $FILE
done < tmp

# Print page footer
cat >> $FILE <<FOOTER
<hr> (c) CC - Mer&eacute;nyi D&aacute;niel
<br>Eredeti: h t t p : / / i n d e x . h u / n a p i r a j z /
<p>Ez az oldal azok sz&aacute;m&aacute;ra k&eacute;sz&uuml;lt,
akiket a c&eacute;ges internet proxy megfosztott a napi rajz
ny&uacute;jtotta inspir&aacute;ci&oacute;t&oacute;l.
<hr>Friss&iacute;tve: `date "+%Y.%m.%d - %H:%M"`
<br><small><a href="http://github.com/subogero">github.com/subogero</a></small>
</body></html>
FOOTER

# Return value is generated filename
echo $FILE
