#!/bin/sh

for WORD in "$@"; do
  case $WORD in
    -*)  true ;
      case $WORD in
        -b)
          shift
          BASE_URL=$1
          shift
          ;;
        -i)
          shift
          INPUT_HTML=$1
          shift
          ;;
        -h)
          cat <<EOF
Usage: ./comedy-rss -b http://base/url/of/your/directory -i parse_this.html [-h]

Create rss file from the jpg link of the input html file. The jpeg files are handled as local files.
The name of the rss file will be created from the input file with extension replacement (html->rss).

Options:
  h  print this help and exit
  b  url of the working directory
     $BASE_URL environment variable can be used instead of it
  i  input html file
     $INPUT_HTML environment variable can be used instead of it
EOF
          exit 0
          ;;
      esac
      ;;
  esac 
done

FILE=`echo ${INPUT_HTML%.*}.rss`

cat > $FILE << HEADER
<?xml version="1.0"?>
<rss version="2.0">
<channel>
<title>comedy</title>
<link>$BASE_URL</link>
<description>Napirajz @ comedy central</description>
<language>hu</language>
HEADER

PICS=`cat $INPUT_HTML | sed -rn 's/<a href="([^"]+.jpg)">[^<]+<\/a>.*/\1/pg'`
PICS=`ls -rt $PICS`
 
for PIC in $PICS; do 
  LMD=$(ls -gG --full-time $PIC | sed -r 's/[^ ]+ [0-9]+ [0-9]+ ([0-9\.-]+ [0-9:\.]+ [0-9+]+).+/\1/')
  DESC=`echo ${PIC%.*}`
  cat >> $FILE << ITEM
<item>
<title>$DESC</title>
<link>$BASE_URL</link>
<description>src="$BASE_URL/$PIC"</description>
<pubDate>$LMD</pubDate>
</item>
ITEM
done



cat >> $FILE << FOOTER
</channel>
</rss> 
FOOTER

echo $FILE
