#!/bin/sh
if [ "$1" = '-h' ]; then cat <<EOF
Usage: ./comedy [ -h ]
Script comedy retrieves Grafitember comics from www.comedycentral.hu,
downloads the comics and creates comedy.html with links to them.
ATTENTION developer: do not print anything else to stdout!!!
EOF
exit 0
fi

# Get picture URLs
URL="http://www.comedycentral.hu/photos/007_cruton/?flipbook=napirajz-comedy-2012-1 \
     http://www.comedycentral.hu/photos/01_csigolyaid/?flipbook=napirajz-comedy"
FILE="komedia.html"
PICS=`curl $URL 2>/dev/null \
| sed -rn 's:^.+src=.(.+)\?(width=70|height=53).+Grafitember.+$:\1:p'`

# Print page header
which perl >/dev/null && EXTENSION=pl || EXTENSION=cgi
cat > $FILE <<HEADER
<html><head><title>subogero kom&eacute;dia</title></head><body>
<a href="index.html">napi</a>
<a href="tegnapi.html">tegnapi</a>
<a href="komedia.html">kom&eacute;dia</a>
<a href="aindex.html">aindex</a>
<a href="keres.${EXTENSION}">keres</a>
<hr><h3 align="center">subogero kom&eacute;dia</h3><hr>
HEADER

# Get pictures and print links to copies
uname -a | grep -i wrt >/dev/null || WGETOPT=-nc
for i in $PICS; do
  wget ${WGETOPT} "${i}"
  echo $i \
  | sed -r 's,^.+/([-A-Za-z0-9_]+)(\.[jpegJPG]+)$,<a href=\"mutat.pl?rajz=\1\2\">\1</a><br>,'
done >> $FILE

# Print page footer
cat >> $FILE <<FOOTER
<hr> (c) CC - Mer&eacute;nyi D&aacute;niel
<br>Eredeti: h t t p : / / w w w . c o m e d y c e n t r a l . h u
<br>Akiknek a nev&eacute;ben &eacute;n k&eacute;rek eln&eacute;z&eacute;st,
hogy a rajzok sorrendje ennyire kaotikus.
<p>Ez az oldal azok sz&aacute;m&aacute;ra k&eacute;sz&uuml;lt,
akiket a c&eacute;ges internet proxy megfosztott a napi rajz
ny&uacute;jtotta inspir&aacute;ci&oacute;t&oacute;l.
<hr>Friss&iacute;tve: `date "+%Y.%m.%d - %H:%M"`
<br><small><a href="http://github.com/subogero">github.com/subogero</a></small>
</body></html>
FOOTER

# Return value is generated filename
echo $FILE
