#!/bin/sh

if [ "$1" = "-h" ]; then
cat <<EOF
Usage: ./comedy-rss [-h] [-t <title>] [-e <description>] -d <dir-url> -i <input-html>

Options:
  -h               print this help and exit
  -d <dir-url>     url of the working directory
                   \$DIR_URL environment variable can be used instead
  -l <dir-loc>     local directory where the pictures are stored
                   \$DIR_LOC environment variable can be used instead
  -i <input-csv>   input file to parse
                   \$INPUT_CSV environment variable can be used instead
  -t <title>       title of the rss channel
                   default if 'comedy'
  -e <description> description of the rss channel
                   default is 'Napirajz @ comedy central'
Create rss file from jpg links in the input html file. 
The jpg files are handled as local files.
The rss file's name reflects the input file, with extension changed to rss.
EOF
exit 0
fi

description='Napirajz @ comedy central'
title='comedy'

while [ -n "$*" ]; do
  if [ "$1" = "-d" ]; then
    shift
    DIR_URL=$1
    shift
  fi
  if [ "$1" = "-l" ]; then
    shift
    DIR_LOC=$1
    shift
  fi
  if [ "$1" = "-i" ]; then
    shift
    INPUT_CSV=$1
    shift
  fi
  if [ "$1" = "-t" ]; then
    shift
    title=$1
    shift
  fi
  if [ "$1" = "-e" ]; then
    shift
    description=$1
    shift
  else
    if [ -n "$1" ]; then
      echo >&2 "Invalid option: $1"
      shift
    fi
  fi
done

if [ -z "$DIR_URL" ]; then
  exit 1
fi
if [ -z "$DIR_LOC" ]; then
  exit 1
fi
if [ -z "$INPUT_CSV" ]; then
  exit 1
fi

FILE=`echo ${INPUT_CSV%.*}.rss`

cat > $FILE << HEADER
<?xml version="1.0"?>
<rss version="2.0">
<channel>
<title>$title</title>
<link>$DIR_URL</link>
<description>$description</description>
<language>hu</language>
HEADER

IFS=';'
while read PIC DATE SRC; do 
  LMD=`ls -le $DIR_LOC/$PIC \
  | sed -r 's/^[-a-z]+ +[0-9]+ +[a-z0-9]+ +[a-z0-9]+ +[0-9]+ +(.+) +[^ ]+$/\1/' \
  | sed -r 's/^(.+) (.+) (.+) (.+) (.+)$/\1, \3 \2 \5 \4 +0100/'`
  DESC=${PIC%.*}
  cat >> $FILE << ITEM
<item>
<title>$DESC from $SRC</title>
<link>$DIR_URL/$PIC</link>
<description>&lt;img src="$DIR_URL/$PIC"/&gt;</description>
<pubDate>$LMD</pubDate>
</item>
ITEM
done < $INPUT_CSV 


cat >> $FILE << FOOTER
</channel>
</rss> 
FOOTER

echo $FILE
