#!/bin/sh
if [ "$1" = '-h' ]; then cat <<EOF
tegnapi retrieves webpage http://napirajz.hu/archives/, extracts links to
monthly archive pages, and creates mirrors for them using script ./napi.
Also creates tegnapi.html with links to the monthly mirrirs.
EOF
exit 0
fi

FILE=tegnapi.html
# Try to get archives, or exit to avoid deleting data, get monthly URLs
curl -f "http://napirajz.hu/archives/" >tmp || exit 1 
PAGES=`cat tmp \
| sed -nr 's,^.+<li><a href=\"(http://napirajz.hu/archives/[0-9]{4}/[0-9]{2}/)\".+$,\1,p'`

# Print page header
cat > $FILE <<HEADER
<html><head><title>subogero tegnapi</title></head>
<body><hr><h1 align="center">subogero tegnapi</h1><hr>
<a href="keres.pl">keres</a><p>
HEADER

# Create page for each month
for i in $PAGES; do
  PAGE=`./napi $i`
  if [ -n "$PAGE" ]; then
    echo '<a href="'${PAGE}'">' >> $FILE
    echo $PAGE | sed -r 's,^(.+)\.html$,\1</a><br>,' >> $FILE
  fi
done

# Print page footer
cat >> $FILE <<FOOTER
<hr> (c) CC - Mer&eacute;nyi D&aacute;niel
<br>Eredeti: h t t p : / / n a p i r a j z . h u
<p>Ez az oldal azok sz&aacute;m&aacute;ra k&eacute;sz&uuml;lt,
akiket a c&eacute;ges internet proxy megfosztott a napi rajz
ny&uacute;jtotta inspir&aacute;ci&oacute;t&oacute;l.
<hr>Friss&iacute;tve: `date "+%Y.%m.%d - %H:%M"`
</body></html>
FOOTER

